[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "yarn cache clean",
  "yarn install --frozen-lockfile --network-timeout 100000"
]
cacheDirectories = []

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "node dist/server.js"

[variables]
NODE_ENV = "production"
PAYLOAD_CONFIG_PATH = "dist/payload.config.js"