name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_PASS }}
        known_hosts: |
          93.127.223.154

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@93.127.223.154 "
        cd /var/www/hkacademy &&
        git pull origin main &&
        yarn install &&
        pm2 restart hkacademy
        "