name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.13.0'

    - name: Copy .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Install dependencies
      run: yarn install

    - name: Build application
      run: yarn build

    - name: SSH into server and deploy
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SERVER_IP <<EOF
          cd /var/www/hkacademy
          # pm2 stop hkacademy
          # Remove old build files
          rm -rf .next build dist .env
          # Copy new build files from GitHub runner to VPS
          mkdir -p .next build dist
          scp -r $GITHUB_WORKSPACE/.next/* $SSH_USERNAME@$SERVER_IP:/var/www/hkacademy/.next/
          scp -r $GITHUB_WORKSPACE/build/* $SSH_USERNAME@$SERVER_IP:/var/www/hkacademy/build/
          scp -r $GITHUB_WORKSPACE/dist/* $SSH_USERNAME@$SERVER_IP:/var/www/hkacademy/dist/
          echo "${{ secrets.ENV_FILE }}" > .env
          pm2 start hkacademy
        EOF
