name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: yarn install

    - name: SSH into server and deploy
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<EOF
          cd /var/www/hkacademy
          git pull origin main
          npx update-browserslist-db@latest
          yarn install
          pm2 stop hkacademy
          NODE_OPTIONS='--max-old-space-size=1604' yarn build
          pm2 start hkacademy
        EOF
